kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: web-data
  storageClassName: ""
