apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: {{ .Values.volumes.hostPath }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
