kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: put-ip-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: ip-data
  storageClassName: ""
